// ⚠️ GERADO AUTOMATICAMENTE. NÃO EDITE NA MÃO.
export type EmotionType = 'alegria' | 'desprezo' | 'medo' | 'nojo' | 'raiva' | 'supresa' | 'tristeza';
export type LevelType = 'nivel1' | 'nivel2' | 'nivel3' | 'nivel4';

export const EXPRESSION_ASSETS: Record<string, Record<string, any[]>> = {
  'alegria': {
    'nivel1': [
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (10).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (11).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (12).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (13).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (2).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (3).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (4).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (5).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (6).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (7).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (8).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia (9).jpg'),
      require('../../assets/expressoes/alegria/nivel1/9 - Copia.jpg'),
      require('../../assets/expressoes/alegria/nivel1/9.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (10).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (11).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (12).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (13).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (14).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (2).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (3).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (4).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (5).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (6).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (7).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (8).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia (9).jpg'),
      require('../../assets/expressoes/alegria/nivel2/10 - Copia.jpg'),
      require('../../assets/expressoes/alegria/nivel2/10.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (10).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (11).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (12).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (13).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (2).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (3).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (4).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (5).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (6).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (7).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (8).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia (9).jpg'),
      require('../../assets/expressoes/alegria/nivel3/11 - Copia.jpg'),
      require('../../assets/expressoes/alegria/nivel3/11.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (10).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (11).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (12).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (13).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (14).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (15).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (2).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (3).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (4).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (5).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (6).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (7).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (8).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia (9).jpg'),
      require('../../assets/expressoes/alegria/nivel4/12 - Copia.jpg'),
      require('../../assets/expressoes/alegria/nivel4/12.jpg'),
    ],
  },
  'desprezo': {
    'nivel1': [
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (10).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (11).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (2).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (3).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (4).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (5).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (6).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (7).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (8).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia (9).jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25 - Copia.jpg'),
      require('../../assets/expressoes/desprezo/nivel1/25.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (10).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (11).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (12).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (13).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (14).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (2).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (3).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (4).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (5).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (6).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (7).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (8).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia (9).jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26 - Copia.jpg'),
      require('../../assets/expressoes/desprezo/nivel2/26.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (10).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (11).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (12).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (2).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (3).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (4).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (5).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (6).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (7).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (8).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia (9).jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27 - Copia.jpg'),
      require('../../assets/expressoes/desprezo/nivel3/27.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (2).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (3).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (4).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (5).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (6).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (7).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (8).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia (9).jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28 - Copia.jpg'),
      require('../../assets/expressoes/desprezo/nivel4/28.jpg'),
    ],
  },
  'medo': {
    'nivel1': [
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (10).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (11).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (12).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (13).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (14).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (15).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (2).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (3).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (4).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (5).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (6).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (7).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (8).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia (9).jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel1/medonivel1b.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/medo/nivel2/medonivel1b (10) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (11) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (12) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (13) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (14) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (2) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (2).jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (3) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (4) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (5) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (6) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (7) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (8) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel2/medonivel1b (9) - Copia.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/medo/nivel3/medonivel1b (10) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (11) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (12) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (13) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (14) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (15) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (16) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (3) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (3).jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (4) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (5) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (6) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (7) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (8) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel3/medonivel1b (9) - Copia.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/medo/nivel4/medonivel1b (10) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (11) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (12) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (13) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (14) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (15) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (16) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (17) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (4) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (4).jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (5) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (6) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (7) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (8) - Copia.jpg'),
      require('../../assets/expressoes/medo/nivel4/medonivel1b (9) - Copia.jpg'),
    ],
  },
  'nojo': {
    'nivel1': [
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (10).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (11).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (12).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (13).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (2).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (3).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (4).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (5).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (6).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (7).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (8).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia (9).jpg'),
      require('../../assets/expressoes/nojo/nivel1/21 - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel1/21.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (10).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (11).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (12).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (13).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (2).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (3).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (4).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (5).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (6).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (7).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (8).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia (9).jpg'),
      require('../../assets/expressoes/nojo/nivel2/22 - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel2/22.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (10) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (11) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (2) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (2).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (3) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (3).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (4) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (4).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (5) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (5).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (6) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (6).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (7) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (7).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (8) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (8).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia (9) - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia - Copia (2).jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23 - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel3/23.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (10).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (11).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (12).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (13).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (2).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (3).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (4).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (5).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (6).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (7).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (8).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia (9).jpg'),
      require('../../assets/expressoes/nojo/nivel4/24 - Copia.jpg'),
      require('../../assets/expressoes/nojo/nivel4/24.jpg'),
    ],
  },
  'raiva': {
    'nivel1': [
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (10).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (11).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (2).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (3).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (4).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (5).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (6).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (7).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (8).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia (9).jpg'),
      require('../../assets/expressoes/raiva/nivel1/5 - Copia.jpg'),
      require('../../assets/expressoes/raiva/nivel1/5.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (10).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (11).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (2).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (3).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (4).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (5).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (6).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (7).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (8).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia (9).jpg'),
      require('../../assets/expressoes/raiva/nivel2/6 - Copia.jpg'),
      require('../../assets/expressoes/raiva/nivel2/6.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (10).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (11).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (12).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (13).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (2).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (3).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (4).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (5).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (6).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (7).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (8).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia (9).jpg'),
      require('../../assets/expressoes/raiva/nivel3/7 - Copia.jpg'),
      require('../../assets/expressoes/raiva/nivel3/7.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (10).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (11).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (12).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (2).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (3).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (4).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (5).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (6).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (7).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (8).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia (9).jpg'),
      require('../../assets/expressoes/raiva/nivel4/8 - Copia.jpg'),
      require('../../assets/expressoes/raiva/nivel4/8.jpg'),
    ],
  },
  'supresa': {
    'nivel1': [
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (10).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (11).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (12).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (2).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (3).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (4).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (5).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (6).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (7).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (8).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia (9).jpg'),
      require('../../assets/expressoes/supresa/nivel1/17 - Copia.jpg'),
      require('../../assets/expressoes/supresa/nivel1/17.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (10).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (2).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (3).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (4).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (5).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (6).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (7).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (8).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia (9).jpg'),
      require('../../assets/expressoes/supresa/nivel2/18 - Copia.jpg'),
      require('../../assets/expressoes/supresa/nivel2/18.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (10).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (2).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (3).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (4).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (5).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (6).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (7).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (8).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia (9).jpg'),
      require('../../assets/expressoes/supresa/nivel3/19 - Copia.jpg'),
      require('../../assets/expressoes/supresa/nivel3/19.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (10).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (2).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (3).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (4).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (5).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (6).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (7).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (8).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia (9).jpg'),
      require('../../assets/expressoes/supresa/nivel4/20 - Copia.jpg'),
      require('../../assets/expressoes/supresa/nivel4/20.jpg'),
    ],
  },
  'tristeza': {
    'nivel1': [
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (2).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (3).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (4).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (5).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (6).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (7).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (8).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia (9).jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13 - Copia.jpg'),
      require('../../assets/expressoes/tristeza/nivel1/13.jpg'),
    ],
    'nivel2': [
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (2).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (3).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (4).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (5).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (6).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (7).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (8).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia (9).jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14 - Copia.jpg'),
      require('../../assets/expressoes/tristeza/nivel2/14.jpg'),
    ],
    'nivel3': [
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (2).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (3).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (4).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (5).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (6).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (7).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia (8).jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15 - Copia.jpg'),
      require('../../assets/expressoes/tristeza/nivel3/15.jpg'),
    ],
    'nivel4': [
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (10).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (2).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (3).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (4).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (5).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (6).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (7).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (8).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia (9).jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16 - Copia.jpg'),
      require('../../assets/expressoes/tristeza/nivel4/16.jpg'),
    ],
  },
};
