export const MONSTER_PARTS = {
  // --- BRAÇOS (30 variações) ---
  arms: {
    blueA: require('../../assets/sprites/Double/arm_blueA.png'),
    blueB: require('../../assets/sprites/Double/arm_blueB.png'),
    blueC: require('../../assets/sprites/Double/arm_blueC.png'),
    blueD: require('../../assets/sprites/Double/arm_blueD.png'),
    blueE: require('../../assets/sprites/Double/arm_blueE.png'),
    darkA: require('../../assets/sprites/Double/arm_darkA.png'),
    darkB: require('../../assets/sprites/Double/arm_darkB.png'),
    darkC: require('../../assets/sprites/Double/arm_darkC.png'),
    darkD: require('../../assets/sprites/Double/arm_darkD.png'),
    darkE: require('../../assets/sprites/Double/arm_darkE.png'),
    greenA: require('../../assets/sprites/Double/arm_greenA.png'),
    greenB: require('../../assets/sprites/Double/arm_greenB.png'),
    greenC: require('../../assets/sprites/Double/arm_greenC.png'),
    greenD: require('../../assets/sprites/Double/arm_greenD.png'),
    greenE: require('../../assets/sprites/Double/arm_greenE.png'),
    redA: require('../../assets/sprites/Double/arm_redA.png'),
    redB: require('../../assets/sprites/Double/arm_redB.png'),
    redC: require('../../assets/sprites/Double/arm_redC.png'),
    redD: require('../../assets/sprites/Double/arm_redD.png'),
    redE: require('../../assets/sprites/Double/arm_redE.png'),
    whiteA: require('../../assets/sprites/Double/arm_whiteA.png'),
    whiteB: require('../../assets/sprites/Double/arm_whiteB.png'),
    whiteC: require('../../assets/sprites/Double/arm_whiteC.png'),
    whiteD: require('../../assets/sprites/Double/arm_whiteD.png'),
    whiteE: require('../../assets/sprites/Double/arm_whiteE.png'),
    yellowA: require('../../assets/sprites/Double/arm_yellowA.png'),
    yellowB: require('../../assets/sprites/Double/arm_yellowB.png'),
    yellowC: require('../../assets/sprites/Double/arm_yellowC.png'),
    yellowD: require('../../assets/sprites/Double/arm_yellowD.png'),
    yellowE: require('../../assets/sprites/Double/arm_yellowE.png'),
  },

  // --- CORPOS (36 variações) ---
  bodies: {
    blueA: require('../../assets/sprites/Double/body_blueA.png'),
    blueB: require('../../assets/sprites/Double/body_blueB.png'),
    blueC: require('../../assets/sprites/Double/body_blueC.png'),
    blueD: require('../../assets/sprites/Double/body_blueD.png'),
    blueE: require('../../assets/sprites/Double/body_blueE.png'),
    blueF: require('../../assets/sprites/Double/body_blueF.png'),
    darkA: require('../../assets/sprites/Double/body_darkA.png'),
    darkB: require('../../assets/sprites/Double/body_darkB.png'),
    darkC: require('../../assets/sprites/Double/body_darkC.png'),
    darkD: require('../../assets/sprites/Double/body_darkD.png'),
    darkE: require('../../assets/sprites/Double/body_darkE.png'),
    darkF: require('../../assets/sprites/Double/body_darkF.png'),
    greenA: require('../../assets/sprites/Double/body_greenA.png'),
    greenB: require('../../assets/sprites/Double/body_greenB.png'),
    greenC: require('../../assets/sprites/Double/body_greenC.png'),
    greenD: require('../../assets/sprites/Double/body_greenD.png'),
    greenE: require('../../assets/sprites/Double/body_greenE.png'),
    greenF: require('../../assets/sprites/Double/body_greenF.png'),
    redA: require('../../assets/sprites/Double/body_redA.png'),
    redB: require('../../assets/sprites/Double/body_redB.png'),
    redC: require('../../assets/sprites/Double/body_redC.png'),
    redD: require('../../assets/sprites/Double/body_redD.png'),
    redE: require('../../assets/sprites/Double/body_redE.png'),
    redF: require('../../assets/sprites/Double/body_redF.png'),
    whiteA: require('../../assets/sprites/Double/body_whiteA.png'),
    whiteB: require('../../assets/sprites/Double/body_whiteB.png'),
    whiteC: require('../../assets/sprites/Double/body_whiteC.png'),
    whiteD: require('../../assets/sprites/Double/body_whiteD.png'),
    whiteE: require('../../assets/sprites/Double/body_whiteE.png'),
    whiteF: require('../../assets/sprites/Double/body_whiteF.png'),
    yellowA: require('../../assets/sprites/Double/body_yellowA.png'),
    yellowB: require('../../assets/sprites/Double/body_yellowB.png'),
    yellowC: require('../../assets/sprites/Double/body_yellowC.png'),
    yellowD: require('../../assets/sprites/Double/body_yellowD.png'),
    yellowE: require('../../assets/sprites/Double/body_yellowE.png'),
    yellowF: require('../../assets/sprites/Double/body_yellowF.png'),
  },

  // --- DETALHES / ACESSÓRIOS (36 variações) ---
  details: {
    // Antenas
    blueAntennaLarge: require('../../assets/sprites/Double/detail_blue_antenna_large.png'),
    blueAntennaSmall: require('../../assets/sprites/Double/detail_blue_antenna_small.png'),
    darkAntennaLarge: require('../../assets/sprites/Double/detail_dark_antenna_large.png'),
    darkAntennaSmall: require('../../assets/sprites/Double/detail_dark_antenna_small.png'),
    greenAntennaLarge: require('../../assets/sprites/Double/detail_green_antenna_large.png'),
    greenAntennaSmall: require('../../assets/sprites/Double/detail_green_antenna_small.png'),
    redAntennaLarge: require('../../assets/sprites/Double/detail_red_antenna_large.png'),
    redAntennaSmall: require('../../assets/sprites/Double/detail_red_antenna_small.png'),
    whiteAntennaLarge: require('../../assets/sprites/Double/detail_white_antenna_large.png'),
    whiteAntennaSmall: require('../../assets/sprites/Double/detail_white_antenna_small.png'),
    yellowAntennaLarge: require('../../assets/sprites/Double/detail_yellow_antenna_large.png'),
    yellowAntennaSmall: require('../../assets/sprites/Double/detail_yellow_antenna_small.png'),

    // Orelhas
    blueEar: require('../../assets/sprites/Double/detail_blue_ear.png'),
    blueEarRound: require('../../assets/sprites/Double/detail_blue_ear_round.png'),
    darkEar: require('../../assets/sprites/Double/detail_dark_ear.png'),
    darkEarRound: require('../../assets/sprites/Double/detail_dark_ear_round.png'),
    greenEar: require('../../assets/sprites/Double/detail_green_ear.png'),
    greenEarRound: require('../../assets/sprites/Double/detail_green_ear_round.png'),
    redEar: require('../../assets/sprites/Double/detail_red_ear.png'),
    redEarRound: require('../../assets/sprites/Double/detail_red_ear_round.png'),
    whiteEar: require('../../assets/sprites/Double/detail_white_ear.png'),
    whiteEarRound: require('../../assets/sprites/Double/detail_white_ear_round.png'),
    yellowEar: require('../../assets/sprites/Double/detail_yellow_ear.png'),
    yellowEarRound: require('../../assets/sprites/Double/detail_yellow_ear_round.png'),

    // Chifres
    blueHornLarge: require('../../assets/sprites/Double/detail_blue_horn_large.png'),
    blueHornSmall: require('../../assets/sprites/Double/detail_blue_horn_small.png'),
    darkHornLarge: require('../../assets/sprites/Double/detail_dark_horn_large.png'),
    darkHornSmall: require('../../assets/sprites/Double/detail_dark_horn_small.png'),
    greenHornLarge: require('../../assets/sprites/Double/detail_green_horn_large.png'),
    greenHornSmall: require('../../assets/sprites/Double/detail_green_horn_small.png'),
    redHornLarge: require('../../assets/sprites/Double/detail_red_horn_large.png'),
    redHornSmall: require('../../assets/sprites/Double/detail_red_horn_small.png'),
    whiteHornLarge: require('../../assets/sprites/Double/detail_white_horn_large.png'),
    whiteHornSmall: require('../../assets/sprites/Double/detail_white_horn_small.png'),
    yellowHornLarge: require('../../assets/sprites/Double/detail_yellow_horn_large.png'),
    yellowHornSmall: require('../../assets/sprites/Double/detail_yellow_horn_small.png'),

    // Detalhes extras (Olhos decorativos)
    blueEyeDetail: require('../../assets/sprites/Double/detail_blue_eye.png'),
    darkEyeDetail: require('../../assets/sprites/Double/detail_dark_eye.png'),
    greenEyeDetail: require('../../assets/sprites/Double/detail_green_eye.png'),
    redEyeDetail: require('../../assets/sprites/Double/detail_red_eye.png'),
    whiteEyeDetail: require('../../assets/sprites/Double/detail_white_eye.png'),
    yellowEyeDetail: require('../../assets/sprites/Double/detail_yellow_eye.png'),
  },

  // --- OLHOS (17 variações) ---
  eyes: {
    angryBlue: require('../../assets/sprites/Double/eye_angry_blue.png'),
    angryGreen: require('../../assets/sprites/Double/eye_angry_green.png'),
    angryRed: require('../../assets/sprites/Double/eye_angry_red.png'),
    blue: require('../../assets/sprites/Double/eye_blue.png'),
    closedFeminine: require('../../assets/sprites/Double/eye_closed_feminine.png'),
    closedHappy: require('../../assets/sprites/Double/eye_closed_happy.png'),
    cuteDark: require('../../assets/sprites/Double/eye_cute_dark.png'),
    cuteLight: require('../../assets/sprites/Double/eye_cute_light.png'),
    dead: require('../../assets/sprites/Double/eye_dead.png'),
    human: require('../../assets/sprites/Double/eye_human.png'),
    humanBlue: require('../../assets/sprites/Double/eye_human_blue.png'),
    humanGreen: require('../../assets/sprites/Double/eye_human_green.png'),
    humanRed: require('../../assets/sprites/Double/eye_human_red.png'),
    psychoDark: require('../../assets/sprites/Double/eye_psycho_dark.png'),
    psychoLight: require('../../assets/sprites/Double/eye_psycho_light.png'),
    red: require('../../assets/sprites/Double/eye_red.png'),
    yellow: require('../../assets/sprites/Double/eye_yellow.png'),
  },

  // --- SOBRANCELHAS (3 variações) ---
  eyebrows: {
    eyebrowA: require('../../assets/sprites/Double/eyebrowA.png'),
    eyebrowB: require('../../assets/sprites/Double/eyebrowB.png'),
    eyebrowC: require('../../assets/sprites/Double/eyebrowC.png'),
  },

  // --- PERNAS (30 variações) ---
  legs: {
    blueA: require('../../assets/sprites/Double/leg_blueA.png'),
    blueB: require('../../assets/sprites/Double/leg_blueB.png'),
    blueC: require('../../assets/sprites/Double/leg_blueC.png'),
    blueD: require('../../assets/sprites/Double/leg_blueD.png'),
    blueE: require('../../assets/sprites/Double/leg_blueE.png'),
    darkA: require('../../assets/sprites/Double/leg_darkA.png'),
    darkB: require('../../assets/sprites/Double/leg_darkB.png'),
    darkC: require('../../assets/sprites/Double/leg_darkC.png'),
    darkD: require('../../assets/sprites/Double/leg_darkD.png'),
    darkE: require('../../assets/sprites/Double/leg_darkE.png'),
    greenA: require('../../assets/sprites/Double/leg_greenA.png'),
    greenB: require('../../assets/sprites/Double/leg_greenB.png'),
    greenC: require('../../assets/sprites/Double/leg_greenC.png'),
    greenD: require('../../assets/sprites/Double/leg_greenD.png'),
    greenE: require('../../assets/sprites/Double/leg_greenE.png'),
    redA: require('../../assets/sprites/Double/leg_redA.png'),
    redB: require('../../assets/sprites/Double/leg_redB.png'),
    redC: require('../../assets/sprites/Double/leg_redC.png'),
    redD: require('../../assets/sprites/Double/leg_redD.png'),
    redE: require('../../assets/sprites/Double/leg_redE.png'),
    whiteA: require('../../assets/sprites/Double/leg_whiteA.png'),
    whiteB: require('../../assets/sprites/Double/leg_whiteB.png'),
    whiteC: require('../../assets/sprites/Double/leg_whiteC.png'),
    whiteD: require('../../assets/sprites/Double/leg_whiteD.png'),
    whiteE: require('../../assets/sprites/Double/leg_whiteE.png'),
    yellowA: require('../../assets/sprites/Double/leg_yellowA.png'),
    yellowB: require('../../assets/sprites/Double/leg_yellowB.png'),
    yellowC: require('../../assets/sprites/Double/leg_yellowC.png'),
    yellowD: require('../../assets/sprites/Double/leg_yellowD.png'),
    yellowE: require('../../assets/sprites/Double/leg_yellowE.png'),
  },

  // --- BOCAS (14 variações) ---
  mouths: {
    mouthA: require('../../assets/sprites/Double/mouthA.png'),
    mouthB: require('../../assets/sprites/Double/mouthB.png'),
    mouthC: require('../../assets/sprites/Double/mouthC.png'),
    mouthD: require('../../assets/sprites/Double/mouthD.png'),
    mouthE: require('../../assets/sprites/Double/mouthE.png'),
    mouthF: require('../../assets/sprites/Double/mouthF.png'),
    mouthG: require('../../assets/sprites/Double/mouthG.png'),
    mouthH: require('../../assets/sprites/Double/mouthH.png'),
    mouthI: require('../../assets/sprites/Double/mouthI.png'),
    mouthJ: require('../../assets/sprites/Double/mouthJ.png'),
    closedFangs: require('../../assets/sprites/Double/mouth_closed_fangs.png'),
    closedHappy: require('../../assets/sprites/Double/mouth_closed_happy.png'),
    closedSad: require('../../assets/sprites/Double/mouth_closed_sad.png'),
    closedTeeth: require('../../assets/sprites/Double/mouth_closed_teeth.png'),
  },

  // --- NARIZES (4 variações) ---
  noses: {
    brown: require('../../assets/sprites/Double/nose_brown.png'),
    green: require('../../assets/sprites/Double/nose_green.png'),
    red: require('../../assets/sprites/Double/nose_red.png'),
    yellow: require('../../assets/sprites/Double/nose_yellow.png'),
  },

  // --- ADICIONAIS / MELECA (2 variações) ---
  snots: {
    large: require('../../assets/sprites/Double/snot_large.png'),
    small: require('../../assets/sprites/Double/snot_small.png'),
  },
};