import { MONSTER_PARTS } from './monsterParts';

export interface ShopItem {
  id: string;
  name: string;
  category: 'bodies' | 'eyes' | 'mouths' | 'arms' | 'legs' | 'details';
  partKey: string;
  price: number;
  levelRequired: number;
  description: string;
}

export const SHOP_ITEMS: ShopItem[] = [
  // ==========================================
  // CORPOS (BODIES) - CATÁLOGO COMPLETO
  // ==========================================
  // Azul (Blue)
  {
    id: 'body_blueA',
    name: 'Cubo Azul',
    category: 'bodies',
    partKey: 'blueA',
    price: 0,
    levelRequired: 1,
    description: 'O corpo quadrado clássico azul.',
  },
  {
    id: 'body_blueB',
    name: 'Redondo Azul',
    category: 'bodies',
    partKey: 'blueB',
    price: 15,
    levelRequired: 2,
    description: 'Um corpinho redondo e fofo.',
  },
  {
    id: 'body_blueC',
    name: 'Gota Azul',
    category: 'bodies',
    partKey: 'blueC',
    price: 25,
    levelRequired: 3,
    description: 'Formato alongado e simpático.',
  },
  {
    id: 'body_blueD',
    name: 'Oval Azul',
    category: 'bodies',
    partKey: 'blueD',
    price: 35,
    levelRequired: 4,
    description: 'Corpo ovalado e espaçoso.',
  },
  {
    id: 'body_blueE',
    name: 'Alto Azul',
    category: 'bodies',
    partKey: 'blueE',
    price: 50,
    levelRequired: 5,
    description: 'Um gigante azul e amigável.',
  },
  {
    id: 'body_blueF',
    name: 'Pera Azul',
    category: 'bodies',
    partKey: 'blueF',
    price: 65,
    levelRequired: 6,
    description: 'Base larga com curvas divertidas.',
  },

  // Verde (Green)
  {
    id: 'body_greenA',
    name: 'Cubo Verde',
    category: 'bodies',
    partKey: 'greenA',
    price: 20,
    levelRequired: 2,
    description: 'Corpo quadrado esmeralda.',
  },
  {
    id: 'body_greenB',
    name: 'Redondo Verde',
    category: 'bodies',
    partKey: 'greenB',
    price: 30,
    levelRequired: 3,
    description: 'Formato de bolha verde saltitante.',
  },
  {
    id: 'body_greenC',
    name: 'Gota Verde',
    category: 'bodies',
    partKey: 'greenC',
    price: 40,
    levelRequired: 4,
    description: 'Estilo alienígena da floresta.',
  },
  {
    id: 'body_greenD',
    name: 'Oval Verde',
    category: 'bodies',
    partKey: 'greenD',
    price: 50,
    levelRequired: 5,
    description: 'Corpo robusto e energético.',
  },
  {
    id: 'body_greenE',
    name: 'Alto Verde',
    category: 'bodies',
    partKey: 'greenE',
    price: 65,
    levelRequired: 6,
    description: 'Monstro alto como uma árvore.',
  },
  {
    id: 'body_greenF',
    name: 'Pera Verde',
    category: 'bodies',
    partKey: 'greenF',
    price: 80,
    levelRequired: 7,
    description: 'Silhueta alegre de pera verde.',
  },

  // Vermelho (Red)
  {
    id: 'body_redA',
    name: 'Cubo Rubi',
    category: 'bodies',
    partKey: 'redA',
    price: 25,
    levelRequired: 3,
    description: 'Corpo avermelhado cheio de energia.',
  },
  {
    id: 'body_redB',
    name: 'Redondo Rubi',
    category: 'bodies',
    partKey: 'redB',
    price: 35,
    levelRequired: 4,
    description: 'Uma esfera vermelha corajosa.',
  },
  {
    id: 'body_redC',
    name: 'Gota Rubi',
    category: 'bodies',
    partKey: 'redC',
    price: 45,
    levelRequired: 5,
    description: 'Chama ardente em formato de gota.',
  },
  {
    id: 'body_redD',
    name: 'Oval Rubi',
    category: 'bodies',
    partKey: 'redD',
    price: 55,
    levelRequired: 6,
    description: 'Forte e destemido.',
  },
  {
    id: 'body_redE',
    name: 'Alto Rubi',
    category: 'bodies',
    partKey: 'redE',
    price: 70,
    levelRequired: 7,
    description: 'Grande presença vermelha.',
  },
  {
    id: 'body_redF',
    name: 'Pera Rubi',
    category: 'bodies',
    partKey: 'redF',
    price: 85,
    levelRequired: 8,
    description: 'Base ampla com cor viva e brilhante.',
  },

  // Escuro / Roxo (Dark)
  {
    id: 'body_darkA',
    name: 'Cubo Sombrio',
    category: 'bodies',
    partKey: 'darkA',
    price: 30,
    levelRequired: 3,
    description: 'Quadrado misterioso e estiloso.',
  },
  {
    id: 'body_darkB',
    name: 'Redondo Sombrio',
    category: 'bodies',
    partKey: 'darkB',
    price: 40,
    levelRequired: 4,
    description: 'Uma esfera roxa misteriosa.',
  },
  {
    id: 'body_darkC',
    name: 'Gota Sombria',
    category: 'bodies',
    partKey: 'darkC',
    price: 50,
    levelRequired: 5,
    description: 'Silhueta suave das sombras.',
  },
  {
    id: 'body_darkD',
    name: 'Oval Sombrio',
    category: 'bodies',
    partKey: 'darkD',
    price: 60,
    levelRequired: 6,
    description: 'Corpo oval da meia-noite.',
  },
  {
    id: 'body_darkE',
    name: 'Alto Sombrio',
    category: 'bodies',
    partKey: 'darkE',
    price: 75,
    levelRequired: 7,
    description: 'Gigante elegante e noturno.',
  },
  {
    id: 'body_darkF',
    name: 'Pera Sombria',
    category: 'bodies',
    partKey: 'darkF',
    price: 90,
    levelRequired: 8,
    description: 'Base larga em tom roxo escuro.',
  },

  // Amarelo (Yellow)
  {
    id: 'body_yellowA',
    name: 'Cubo Dourado',
    category: 'bodies',
    partKey: 'yellowA',
    price: 35,
    levelRequired: 4,
    description: 'Brilha como os raios de sol.',
  },
  {
    id: 'body_yellowB',
    name: 'Redondo Dourado',
    category: 'bodies',
    partKey: 'yellowB',
    price: 45,
    levelRequired: 5,
    description: 'Uma bolinha de pura alegria amarela.',
  },
  {
    id: 'body_yellowC',
    name: 'Gota Dourada',
    category: 'bodies',
    partKey: 'yellowC',
    price: 55,
    levelRequired: 6,
    description: 'Gota luminosa e radiante.',
  },
  {
    id: 'body_yellowD',
    name: 'Oval Dourado',
    category: 'bodies',
    partKey: 'yellowD',
    price: 65,
    levelRequired: 7,
    description: 'Grande e reluzente.',
  },
  {
    id: 'body_yellowE',
    name: 'Alto Dourado',
    category: 'bodies',
    partKey: 'yellowE',
    price: 80,
    levelRequired: 8,
    description: 'Uma torre dourada de simpatia.',
  },
  {
    id: 'body_yellowF',
    name: 'Pera Dourada',
    category: 'bodies',
    partKey: 'yellowF',
    price: 95,
    levelRequired: 9,
    description: 'Silhueta vibrante e acolhedora.',
  },

  // Branco (White)
  {
    id: 'body_whiteA',
    name: 'Cubo Nuvem',
    category: 'bodies',
    partKey: 'whiteA',
    price: 40,
    levelRequired: 5,
    description: 'Puro e fofo como algodão.',
  },
  {
    id: 'body_whiteB',
    name: 'Redondo Nuvem',
    category: 'bodies',
    partKey: 'whiteB',
    price: 50,
    levelRequired: 6,
    description: 'Parece uma bolinha de neve suave.',
  },
  {
    id: 'body_whiteC',
    name: 'Gota Nuvem',
    category: 'bodies',
    partKey: 'whiteC',
    price: 60,
    levelRequired: 7,
    description: 'Suave e delicado como uma nuvem.',
  },
  {
    id: 'body_whiteD',
    name: 'Oval Nuvem',
    category: 'bodies',
    partKey: 'whiteD',
    price: 70,
    levelRequired: 8,
    description: 'Espaçoso e sereno.',
  },
  {
    id: 'body_whiteE',
    name: 'Alto Nuvem',
    category: 'bodies',
    partKey: 'whiteE',
    price: 85,
    levelRequired: 9,
    description: 'Um gigante das alturas celestiais.',
  },
  {
    id: 'body_whiteF',
    name: 'Pera Nuvem',
    category: 'bodies',
    partKey: 'whiteF',
    price: 100,
    levelRequired: 10,
    description: 'O corpo lendário das nuvens.',
  },

  // ==========================================
  // OLHOS (EYES)
  // ==========================================
  {
    id: 'eye_cuteLight',
    name: 'Olhar Curioso',
    category: 'eyes',
    partKey: 'cuteLight',
    price: 0,
    levelRequired: 1,
    description: 'Olhos grandes e brilhantes.',
  },
  {
    id: 'eye_closedHappy',
    name: 'Super Feliz',
    category: 'eyes',
    partKey: 'closedHappy',
    price: 10,
    levelRequired: 1,
    description: 'Fechados de tanta alegria.',
  },
  {
    id: 'eye_blue',
    name: 'Azul Vivo',
    category: 'eyes',
    partKey: 'blue',
    price: 15,
    levelRequired: 2,
    description: 'Olhos azuis expressivos.',
  },
  {
    id: 'eye_cuteDark',
    name: 'Preguicinha',
    category: 'eyes',
    partKey: 'cuteDark',
    price: 20,
    levelRequired: 2,
    description: 'Olhos pretos profundos e calmos.',
  },
  {
    id: 'eye_angryRed',
    name: 'Focado Rubi',
    category: 'eyes',
    partKey: 'angryRed',
    price: 25,
    levelRequired: 3,
    description: 'Olhar compenetrado e corajoso.',
  },
  {
    id: 'eye_human',
    name: 'Olhar Humano',
    category: 'eyes',
    partKey: 'human',
    price: 30,
    levelRequired: 3,
    description: 'Pupilas expressivas e detalhadas.',
  },
  {
    id: 'eye_dead',
    name: 'Tonto Divertido',
    category: 'eyes',
    partKey: 'dead',
    price: 35,
    levelRequired: 4,
    description: 'Em formato de X de pura diversão.',
  },
  {
    id: 'eye_psychoLight',
    name: 'Espiral Cósmico',
    category: 'eyes',
    partKey: 'psychoLight',
    price: 45,
    levelRequired: 5,
    description: 'Espirais hipnotizantes e animadas.',
  },

  // ==========================================
  // BOCAS (MOUTHS)
  // ==========================================
  {
    id: 'mouth_closedHappy',
    name: 'Sorriso Doce',
    category: 'mouths',
    partKey: 'closedHappy',
    price: 0,
    levelRequired: 1,
    description: 'Um sorrisinho meigo e tranquilo.',
  },
  {
    id: 'mouth_mouthB',
    name: 'Sorrisão Aberto',
    category: 'mouths',
    partKey: 'mouthB',
    price: 10,
    levelRequired: 1,
    description: 'Boca aberta comemorando a vitória.',
  },
  {
    id: 'mouth_closedTeeth',
    name: 'Sorriso Dentuço',
    category: 'mouths',
    partKey: 'closedTeeth',
    price: 15,
    levelRequired: 2,
    description: 'Mostrando os dentinhos com orgulho.',
  },
  {
    id: 'mouth_closedFangs',
    name: 'Presinhas Fofas',
    category: 'mouths',
    partKey: 'closedFangs',
    price: 20,
    levelRequired: 2,
    description: 'Duas pequenas presas simpáticas.',
  },
  {
    id: 'mouth_mouthH',
    name: 'Gargalhada',
    category: 'mouths',
    partKey: 'mouthH',
    price: 30,
    levelRequired: 3,
    description: 'Rindo alto e contagiando todos.',
  },
  {
    id: 'mouth_closedSad',
    name: 'Pensativo',
    category: 'mouths',
    partKey: 'closedSad',
    price: 15,
    levelRequired: 2,
    description: 'Boca tímida e reflexiva.',
  },

  // ==========================================
  // BRAÇOS (ARMS)
  // ==========================================
  {
    id: 'arm_blueA',
    name: 'Braços Curtos Azuis',
    category: 'arms',
    partKey: 'blueA',
    price: 0,
    levelRequired: 1,
    description: 'Braços azuis padrão.',
  },
  {
    id: 'arm_blueB',
    name: 'Bracinhos Finos Azuis',
    category: 'arms',
    partKey: 'blueB',
    price: 15,
    levelRequired: 2,
    description: 'Braços finos e ágeis.',
  },
  {
    id: 'arm_greenA',
    name: 'Braços Fortes Verdes',
    category: 'arms',
    partKey: 'greenA',
    price: 20,
    levelRequired: 2,
    description: 'Braços verdes de herói.',
  },
  {
    id: 'arm_redA',
    name: 'Braços Valentes Vermelhos',
    category: 'arms',
    partKey: 'redA',
    price: 25,
    levelRequired: 3,
    description: 'Braços rubis musculosos.',
  },
  {
    id: 'arm_darkA',
    name: 'Braços da Noite',
    category: 'arms',
    partKey: 'darkA',
    price: 30,
    levelRequired: 3,
    description: 'Braços escuros elegantes.',
  },

  // ==========================================
  // PERNAS (LEGS)
  // ==========================================
  {
    id: 'leg_blueA',
    name: 'Patas Azuis',
    category: 'legs',
    partKey: 'blueA',
    price: 0,
    levelRequired: 1,
    description: 'Perninhas firmes azuis.',
  },
  {
    id: 'leg_blueB',
    name: 'Perninhas Finas',
    category: 'legs',
    partKey: 'blueB',
    price: 15,
    levelRequired: 2,
    description: 'Passos rápidos e saltitantes.',
  },
  {
    id: 'leg_greenA',
    name: 'Patas Verdes',
    category: 'legs',
    partKey: 'greenA',
    price: 20,
    levelRequired: 2,
    description: 'Prontas para aventuras na floresta.',
  },
  {
    id: 'leg_redA',
    name: 'Patas Rubis',
    category: 'legs',
    partKey: 'redA',
    price: 25,
    levelRequired: 3,
    description: 'Pernas fortes e estáveis.',
  },
  {
    id: 'leg_darkA',
    name: 'Patas das Sombras',
    category: 'legs',
    partKey: 'darkA',
    price: 30,
    levelRequired: 3,
    description: 'Passos silenciosos e precisos.',
  },

  // ==========================================
  // DETALHES (DETAILS - ORELHAS, CHIFRES, ANTENAS)
  // ==========================================
  {
    id: 'detail_blueAntennaLarge',
    name: 'Antena Grande Azul',
    category: 'details',
    partKey: 'blueAntennaLarge',
    price: 0,
    levelRequired: 1,
    description: 'Captando todas as emoções.',
  },
  {
    id: 'detail_blueAntennaSmall',
    name: 'Antena Curta Azul',
    category: 'details',
    partKey: 'blueAntennaSmall',
    price: 10,
    levelRequired: 1,
    description: 'Discreta e fofinha.',
  },
  {
    id: 'detail_blueEar',
    name: 'Orelhas Pontudas Azuis',
    category: 'details',
    partKey: 'blueEar',
    price: 15,
    levelRequired: 2,
    description: 'Para escutar qualquer risada.',
  },
  {
    id: 'detail_blueEarRound',
    name: 'Orelhas Redondas Azuis',
    category: 'details',
    partKey: 'blueEarRound',
    price: 20,
    levelRequired: 2,
    description: 'Estilo ursinho simpático.',
  },
  {
    id: 'detail_blueHornLarge',
    name: 'Chifres Azuis',
    category: 'details',
    partKey: 'blueHornLarge',
    price: 25,
    levelRequired: 3,
    description: 'Chifres mágicos reluzentes.',
  },
  {
    id: 'detail_greenHornLarge',
    name: 'Chifres Verdes',
    category: 'details',
    partKey: 'greenHornLarge',
    price: 30,
    levelRequired: 3,
    description: 'Força da natureza na cabeça.',
  },
  {
    id: 'detail_redEar',
    name: 'Orelhas Rubis',
    category: 'details',
    partKey: 'redEar',
    price: 30,
    levelRequired: 3,
    description: 'Ouvidos atentos a tudo.',
  },
  {
    id: 'detail_darkEarRound',
    name: 'Orelhas Redondas Escuras',
    category: 'details',
    partKey: 'darkEarRound',
    price: 35,
    levelRequired: 4,
    description: 'Visual moderno e misterioso.',
  },
];